### ISSUE TITLE
An API Key is not optional as described in the documentation (TypeScript)

### ISSUE THREAD

**Issue by kaname-png** [zyrouge/genius-lyrics#13]
According to the documentation an API Key is optional, but in TypeScript the typing says it is mandatory.

![image](https://user-images.githubusercontent.com/56084970/110226455-11569780-7eb5-11eb-86a3-b825d7265b5d.png)

**Comment by zyrouge** [comment]
Ah, my bad. I'll fix it and publish tonight.

**Comment by zyrouge** [comment]
Fixed in `v4.2.4` 🎉
