### ISSUE TITLE
.lyrics() method always returns "No result was found".

### ISSUE THREAD

**Issue by programwizard88** [zyrouge/genius-lyrics#16]

**Comment by programwizard88** [comment]
I've seen the other closed issue saying that sometimes it works and sometimes it doesn't and you said that's the disadvantage of scraping (I don't really know what's scraping in programming). But with me, it never worked. It's always "No result was found."

**Comment by zyrouge** [comment]
Seems weird. Would be helpful if you say more about where you ran the code but I'll try my best. :)

**Comment by zyrouge** [comment]
Closing this as it is stale.

**Comment by Kunj-Ahuja** [comment]
same problem!!

**Comment by zyrouge** [comment]
> same problem!!

Create a new issue elaborating your problem, I'll try to help you.
