### ISSUE TITLE
error when search for arabic songs

### ISSUE THREAD

**Issue by Majoramari** [zyrouge/genius-lyrics#5]
hello, i'm trying to search for arabic songs like دا لو اتساب or 3 دقات i'm getting this error
(GeniusLyrics) TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters

**Comment by Snowflake107** [comment]
please use `encodeURIComponent(yourQuery)`

**Comment by zyrouge** [comment]
Fixed in v5
