### ISSUE TITLE
error: No result was found

### ISSUE THREAD

**Issue by Rachniotov** [zyrouge/genius-lyrics#6]
Sometimes when we try to get lyrics with .lyrics() function, it gives us this error: `No result was found` but if we try the same song after some time, it gives us the result. Maybe this is a bug.

**Comment by zyrouge** [comment]
This is only of the disadvantages of scraping. We always can't get consistent result even though it works sometime. Closing this issue with this, reopen this issue if you find it was because of a bug :D
