### ISSUE TITLE
Error: Request failed with status code 403

### ISSUE THREAD

**Issue by Ryanika-Coder** [zyrouge/genius-lyrics#7]

**Comment by zyrouge** [comment]
When did it occur? While using Scrapper Client (no key) or the API (with key)?

**Comment by Ryanika-Coder** [comment]
With key and without key

**Comment by Ryanika-Coder** [comment]
This happens when scraping lyrics.

**Comment by zyrouge** [comment]
Maybe you are making too many requests, try using proxy if so

**Comment by Snowflake107** [comment]
it should return 429 for too many requests no?

**Comment by Ryanika-Coder** [comment]
> it should return 429 for too many requests no?

Ah! Snowflake!
Well... The problem is the hosting service that i use. It running with localhost that make it get CORS.

**Comment by zyrouge** [comment]
> > it should return 429 for too many requests no?
> 
> Ah! Snowflake!
> Well... The problem is the hosting service that i use. It running with localhost that make it get CORS.

Proxy can fix CORS if proxy supports CORS, either way.
