### ISSUE TITLE
Please add support for optional genius api host address

### ISSUE THREAD

**Issue by vitaliikravets** [zyrouge/genius-lyrics#8]
I would like to use this library from browser. 
In order to fight the CORS , improve performance and lower the load on actual API, I am setting up a CDN that will have the same domain name as my website but will redirect all calls to genius.com.

**Comment by zyrouge** [comment]
Soon™

**Comment by zyrouge** [comment]
🎉Added in v4.2.0

**Comment by vitaliikravets** [comment]
Wow @zyrouge that was a very prompt response, thanks!
Is genius website URL **(www.genius.com)** also configurable? To be able to fetch the lyrics from the browser?

**Comment by zyrouge** [comment]
> Wow @zyrouge that was a very prompt response, thanks!
> Is genius website URL **([www.genius.com](http://www.genius.com))** also configurable? To be able to fetch the lyrics from the browser?

Yeah `options.origin.url`
